### ISSUE TITLE
Validate order messages are not translated

### ISSUE THREAD

**Issue by unicoder88** [DIBS-Payment-Services/Magento2_easy#15]
\Dibs\EasyCheckout\Controller\Order\ValidateOrder::execute:

- return $this->respondWithError("Your session has expired, found no dibs payment id.");
- return $this->respondWithError("Your session has expired, found no quote.");
- return $this->respondWithError("Found no Dibs Order for this session. Please refresh the site or clear your cookies.");
- return $this->respondWithError("Something went wrong when we tried to retrieve the order from Dibs. Please try again or contact an admin.");
- return $this->respondWithError("Please add shipping information.");
- return $this->respondWithError("Something went wrong... Contact site admin.");

**Comment by Tim-Badin** [comment]
Hi @unicoder88 
Please use our latest 1.3.1 version in which the controller for validate order is not used anymore. Instead, the validation is moved to the SaveOrder controller, and uses translation function.
