### ISSUE TITLE
Authorized order status

### ISSUE THREAD

**Issue by unicoder88** [DIBS-Payment-Services/Magento2_easy#16]
Hi!

When money is authorized via credit card and order is created order is created in state NEW and status PENDING. I believe this is an error - NEW indicates that no payment was made. Some payments first create order in pending status, then authorize money and change status to PROCESSING.

NEW orders are ignored in reporting, and most integrations.

Looking forward (almost hopelessly) to your reply ;)

**Comment by martinSternelius** [comment]
Hi. Thanks notifying about this issue. We have an upcoming minor release, and after that are planning a more major release. We will include a fix for this in that major one.

**Comment by martinSternelius** [comment]
Hello again. With release 1.3.1, orders are now updated to state PROCESSING after authorization, and there is a new config setting to choose the status.
