### ISSUE TITLE
Invalid Body error on checkout

### ISSUE THREAD

**Issue by prymag** [DIBS-Payment-Services/Magento2_easy#8]
Checkout page encounters Invalid Body error,
Issue happens when the computed tax amount for an item has a decimal.

Dibs\EasyCheckout\Model\Dibs\Items.php Line 232
->setTaxAmount($this->getTotalTaxAmount($unitPrice * $qty, $vat, false))

Removing false seems to solve the issue
->setTaxAmount($this->getTotalTaxAmount($unitPrice * $qty, $vat))

**Comment by martinSternelius** [comment]
Thank you for the input. Issue is no longer present in latest version.
